######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 21 08:53:09 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
