######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 28 18:39:44 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
