######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 08:48:51 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
